import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadQAGuidelines } from "../src/qa/QAGuidelineLoader.ts";
import { QAVectorStore } from "../src/qa/QAVectorStore.ts";
import { maskSecrets, buildEvidence } from "../src/evidence/ProjectEvidenceStore.ts";
import { calculateMetrics, type ComplianceFinding } from "../src/models/Compliance.ts";
import { QAAgent, parseAgentResponse } from "../src/qa/QAAgent.ts";
import type { ScannedFile } from "../src/repository/RepositoryScanner.ts";

test("QA loader separa cada guideline y conserva metadata e ID en el texto", async () => { const guidelines = await loadQAGuidelines(join(process.cwd(), "knowledge", "qa")); assert.equal(guidelines.length, 68); assert.ok(guidelines.every(g => g.text.includes(g.guidelineId) && g.source && g.sourceVersion && g.priority)); assert.equal(new Set(guidelines.map(g => g.guidelineId)).size, guidelines.length); assert.equal(guidelines.find(g => g.guidelineId === "QA-ASVS-004")?.domain, "Security"); assert.equal(guidelines.find(g => g.guidelineId === "QA-GEN-001")?.priority, "HIGH"); assert.equal(guidelines.find(g => g.guidelineId === "QA-SSDF-PS-003")?.sourceVersion, "1.1"); });
test("QA vector store persiste y recupera por dominio", async () => { const root=await mkdtemp(join(tmpdir(),"qa-store-")); try { const gs=await loadQAGuidelines(join(process.cwd(),"knowledge","qa")); const store=await QAVectorStore.open(gs,join(root,"vectors.json")); assert.ok(store.search("testing automated tests",4,["Testing"]).every(g=>g.domain==="Testing")); const second=await QAVectorStore.open(gs,join(root,"vectors.json")); assert.equal(second.search("security secrets",4,["Security"]).length,4); } finally { await rm(root,{recursive:true,force:true}); } });
test("secret masking nunca devuelve el valor completo", () => { const raw="apiKey=sk-1234567890abcdef password='super-secret-value'"; const safe=maskSecrets(raw); assert.doesNotMatch(safe,/1234567890abcdef|super-secret-value/); assert.match(safe,/MASKED|\.\.\./); });
test("evidencia conserva analysisId, rutas relativas y líneas", () => { const files: ScannedFile[]=[{relativePath:"src/Auth.ts",content:"class Auth {\n  login() {\n    return true;\n  }\n}",lines:5,category:"source"}]; const chunks=buildEvidence("a-1",files); assert.equal(chunks[0].analysisId,"a-1"); assert.equal(chunks[0].relativePath,"src/Auth.ts"); assert.ok(chunks[0].startLine>=1 && chunks[0].endLine<=5); });
test("métricas excluyen SIN_EVIDENCIA y NO_APLICA del score", () => { const make=(status:ComplianceFinding["status"]):ComplianceFinding=>({guidelineId:status,title:status,domain:"Testing",source:"test",status,confidence:"HIGH",priority:"LOW",evidence:[],reasoningSummary:"test"}); const m=calculateMetrics([make("CUMPLE"),make("CUMPLE_PARCIALMENTE"),make("NO_CUMPLE"),make("SIN_EVIDENCIA"),make("NO_APLICA")]); assert.equal(m.verifiedComplianceScore,50); assert.equal(m.evidenceCoverage,75); });
test("ausencia de tests es SIN_EVIDENCIA y un secreto directo es NO_CUMPLE", async () => { const gs=await loadQAGuidelines(join(process.cwd(),"knowledge","qa")); const profile={languages:["TypeScript"],frameworks:[],hasFrontend:false,hasBackend:true,hasTests:false,hasCI:false,hasDocker:false,projectType:["api"],databases:[],testingFrameworks:[],filesDetected:1,cloudProviders:[],hasInfrastructure:false,hasAuthentication:false,coverage:"not available" as const,signals:{hasEnvExample:false,hasPotentialSecrets:true,hasCorsSignal:false,packageManagers:[],documentationFiles:0,configFiles:0}}; const evidence=buildEvidence("a",[{relativePath:"src/config.ts",content:"const apiKey = 'abc';",lines:1,category:"source"}]); const found=await new QAAgent("Security").run({analysisId:"a",profile,evidence,guidelines:gs.filter(g=>g.domain==="Security")}); assert.ok(found.some(f=>f.guidelineId==="QA-SSDF-PS-003" && f.status==="NO_CUMPLE")); const testing=await new QAAgent("Testing").run({analysisId:"a",profile,evidence,guidelines:gs.filter(g=>g.domain==="Testing")}); assert.ok(testing.every(f=>f.status==="SIN_EVIDENCIA")); });
test("structured agent response inválida conserva resultados seguros", async () => { const fallback: ComplianceFinding={guidelineId:"QA-TEST-001",title:"Tests",domain:"Testing",source:"test",status:"SIN_EVIDENCIA",confidence:"LOW",priority:"HIGH",evidence:[],reasoningSummary:"fallback"}; const context={analysisId:"a",profile:{languages:[],frameworks:[],hasFrontend:false,hasBackend:false,hasTests:false,hasCI:false,hasDocker:false,projectType:[],databases:[],testingFrameworks:[],filesDetected:0,cloudProviders:[],hasInfrastructure:false,hasAuthentication:false,coverage:"not available" as const,signals:{hasEnvExample:false,hasPotentialSecrets:false,hasCorsSignal:false,packageManagers:[],documentationFiles:0,configFiles:0}},evidence:[],guidelines:[]}; assert.deepEqual(parseAgentResponse("not-json",[fallback],context),[fallback]); assert.deepEqual(parseAgentResponse(JSON.stringify([{guidelineId:"OTHER",reasoningSummary:"invented"}]),[fallback],context),[fallback]); });
