import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import type { Priority } from "../models/Compliance.ts";
import type { QAGuideline } from "./Guideline.ts";
const heading = /^#{2,3}\s+([A-Z0-9-]+)\s+[—-]\s+(.+?)\s*$/gm;
type Frontmatter = Record<string, string>;
export async function loadQAGuidelines(root: string): Promise<QAGuideline[]> { const result: QAGuideline[] = []; for (const file of (await readdir(root)).filter(f => f.endsWith(".md") && !/^00_/.test(f))) { const raw = await readFile(join(root, file), "utf8"); const frontmatter = parseFrontmatter(raw); const matches = [...raw.matchAll(heading)]; for (let i=0;i<matches.length;i++) { const match=matches[i]; const body=raw.slice((match.index??0)+match[0].length,matches[i+1]?.index??raw.length).trim(); const id=match[1]; if(!/^QA-[A-Z0-9-]+$/.test(id))continue; const domain=domainFor(id,frontmatter.domain); const source=frontmatter.source ?? sourceFor(id); const sourceVersion=frontmatter.version ?? "local mapping"; result.push({guidelineId:id,title:match[2].trim(),domain,source,sourceVersion,priority:priorityOf(body),tags:tagsFor(id,body),text:`${id} — ${match[2].trim()}\nSource: ${source}\nSource version: ${sourceVersion}\n${body}`}); } } if(!result.length)throw new Error("No se encontraron guidelines QA locales."); if(new Set(result.map(x=>x.guidelineId)).size!==result.length)throw new Error("Existen guidelineId QA duplicados."); return result; }
function parseFrontmatter(raw:string):Frontmatter { const match=raw.match(/^---\s*\n([\s\S]*?)\n---/); if(!match)return {}; const values:Frontmatter={}; for(const line of match[1].split(/\r?\n/)){const item=line.match(/^([\w-]+):\s*["']?(.+?)["']?\s*$/);if(item)values[item[1]]=item[2];} return values; }
function domainFor(id:string, declared:string|undefined):QAGuideline["domain"] { if(id.startsWith("QA-25010"))return "Product Quality"; if(id.startsWith("QA-TEST"))return "Testing"; if(id.startsWith("QA-ASVS")||id.startsWith("QA-SSDF")||id.startsWith("QA-WSTG"))return "Security"; if(declared==="product_quality")return "Product Quality"; if(declared==="software_testing")return "Testing"; if(declared==="application_security"||declared==="secure_software_development"||declared==="web_security_testing")return "Security"; return "General QA"; }
function sourceFor(id:string):string { if(id.startsWith("QA-25010"))return "ISO/IEC 25010:2023 mapping"; if(id.startsWith("QA-TEST"))return "ISO/IEC/IEEE 29119 mapping"; if(id.startsWith("QA-SSDF"))return "NIST SP 800-218 SSDF mapping"; if(id.startsWith("QA-ASVS"))return "OWASP ASVS mapping"; if(id.startsWith("QA-WSTG"))return "OWASP WSTG mapping"; return "Internal QA policy mapping"; }
function priorityOf(body:string):Priority { const raw=body.match(/\*\*Prioridad:\*\*\s*([^\s*]+)/i)?.[1]?.toLowerCase()??body.match(/^Priority:\s*(\w+)/mi)?.[1]?.toLowerCase()??"medium"; if(/cr[ií]t/.test(raw))return "CRITICAL"; if(/alta|high/.test(raw))return "HIGH"; if(/baja|low/.test(raw))return "LOW"; return "MEDIUM"; }
function tagsFor(id:string,body:string):string[] { const rule=body.match(/\*\*Regla:\*\*([\s\S]*?)(?=\n\s*\*\*|$)/i)?.[1]??body.split(/\r?\n/).slice(0,4).join(" "); const text=`${id} ${rule}`.toLowerCase(); const tags:string[]=[]; const add=(tag:string,pattern:RegExp)=>{if(pattern.test(text))tags.push(tag);}; add("documentation",/documentaci[oó]n|readme|adr|manual/); add("tests",/pruebas?|test|assert|suite/); add("ci",/\bci\b|pipeline|github actions|workflow/); add("source-control",/version|commit|pull request|rama|branch|configuraci[oó]n/); add("error-handling",/error|excepci[oó]n|fallo/); add("secret",/secreto|credencial|password|token|api[_ -]?key/); add("validation",/validaci[oó]n|sanitiz|esquema|schema|entrada/); add("authentication",/autenticaci[oó]n|login|oauth|oidc|jwt|sesi[oó]n/); add("authorization",/autorizaci[oó]n|permiso|privilegio|acceso/); add("cors",/cors|origen/); add("negative-testing",/negativ|inv[aá]lid|rechaz|4xx|5xx/); add("evidence",/evidencia|auditable|trazabilidad/); add("maintainability",/mantenibilidad|modular|complejidad/); add("security",/seguridad|vulnerabilidad|inyecci[oó]n|criptograf/); return [...new Set(tags)]; }
